/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['"Newsreader"', 'serif'],
        body: ['"Inter"', 'sans-serif'],
        label: ['"Inter"', 'sans-serif'],
        sans: ['"Inter"', 'sans-serif'],
        serif: ['"Newsreader"', 'serif'],
      },
      colors: {
        'surface-variant': 'var(--color-surface-variant)',
        'outline-variant': 'var(--color-outline-variant)',
        'on-primary': 'var(--color-on-primary)',
        'surface-dim': 'var(--color-surface-dim)',
        'secondary-container': 'var(--color-secondary-container)',
        'surface-container': 'var(--color-surface-container)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'secondary': 'var(--color-secondary)',
        'outline': 'var(--color-outline)',
        'on-error': 'var(--color-on-error)',
        'on-error-container': 'var(--color-on-error-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'background': 'var(--color-background)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'error': 'var(--color-error)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'error-container': 'var(--color-error-container)',
        'primary-container': 'var(--color-primary-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-surface': 'var(--color-on-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'surface-tint': 'var(--color-surface-tint)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'on-background': 'var(--color-on-background)',
        border: "rgba(255,255,255,0.06)",
        input: "rgba(255,255,255,0.06)",
        ring: "var(--color-primary-fixed)",
        primary: {
          DEFAULT: "var(--color-on-background)",
          foreground: "var(--color-background)",
        },
      },
    },
  },
  plugins: [],
}
